### ISSUE TITLE
JavaScript Capstone Kanban Setup

### ISSUE THREAD

**Issue by Bateyjosue** [Bateyjosue/The-Meal#21]
[Kanban board link](https://github.com/Bateyjosue/javascript-capstone/projects/1)

Hey Reviewer, Here is the link to our Kanban board. 
We work on it as a group of two people @PraisesPJMT  and @Bateyjosue.
Please, consider ignoring the task for student C as we are planning to work on it as an optional feature.

Happy Review :wave: :wave:

**Comment by medaminedev66** [comment]
Hi @Bateyjosue and @PraisesPJMT  😃, :wave:, 

Good job so far!
You still need to work on some issues to go to the next step, but you are almost there!

## Required Changes ♻️
- [ ] Since your team consists of two students, all cards with the Student C suffix on the template should be removed from your template copy.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Bateyjosue** [comment]
Hello, thanks for the review, we made changes as requested you can now check link the below to confirm that...

[Kandan Board](https://github.com/Bateyjosue/javascript-capstone/projects/1)

Happy Review :wave:

**Comment by dasileker** [comment]
### **Hi @Bateyjosue,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
